# These are supported funding model platforms

github: [modelgate]  # Replace with your GitHub username/org
# patreon: modelgate
# open_collective: modelgate
# ko_fi: modelgate
# tidelift: npm/modelgate
# community_bridge: modelgate
# liberapay: modelgate
# issuehunt: modelgate
# otechie: modelgate
# lfx_crowdfunding: modelgate
# custom: ["https://www.buymeacoffee.com/modelgate"]

