// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type APIKey struct {
	ID             string     `json:"id"`
	Name           string     `json:"name"`
	KeyPrefix      string     `json:"keyPrefix"`
	Role           *Role      `json:"role,omitempty"`
	Group          *Group     `json:"group,omitempty"`
	LastUsedAt     *time.Time `json:"lastUsedAt,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
	CreatedBy      *string    `json:"createdBy,omitempty"`
	CreatedByEmail *string    `json:"createdByEmail,omitempty"`
	ExpiresAt      *time.Time `json:"expiresAt,omitempty"`
	IsExpired      bool       `json:"isExpired"`
	Revoked        bool       `json:"revoked"`
}

type APIKeyUsage struct {
	APIKeyID   string  `json:"apiKeyId"`
	APIKeyName string  `json:"apiKeyName"`
	Requests   int     `json:"requests"`
	Tokens     int     `json:"tokens"`
	Cost       float64 `json:"cost"`
	Percentage float64 `json:"percentage"`
}

type APIKeyWithSecret struct {
	APIKey *APIKey `json:"apiKey"`
	Secret string  `json:"secret"`
}

type AddProviderAPIKeyInput struct {
	Provider        Provider `json:"provider"`
	APIKey          *string  `json:"apiKey,omitempty"`
	AccessKeyID     *string  `json:"accessKeyId,omitempty"`
	SecretAccessKey *string  `json:"secretAccessKey,omitempty"`
	Name            *string  `json:"name,omitempty"`
	Priority        int      `json:"priority"`
}

type AdvancedMetrics struct {
	Cache          *CacheMetrics          `json:"cache"`
	Routing        *RoutingMetrics        `json:"routing"`
	Resilience     *ResilienceMetrics     `json:"resilience"`
	ProviderHealth *ProviderHealthMetrics `json:"providerHealth"`
}

type AgentCacheMetrics struct {
	TotalHits   int     `json:"totalHits"`
	TotalMisses int     `json:"totalMisses"`
	HitRate     float64 `json:"hitRate"`
	TokensSaved int     `json:"tokensSaved"`
	CostSaved   float64 `json:"costSaved"`
}

type AgentDashboardStats struct {
	ProviderModelUsage []ProviderModelUsage `json:"providerModelUsage"`
	TokenMetrics       *TokenMetrics        `json:"tokenMetrics"`
	CacheMetrics       *AgentCacheMetrics   `json:"cacheMetrics"`
	ToolCallMetrics    *ToolCallMetrics     `json:"toolCallMetrics"`
	RiskAssessment     *RiskAssessment      `json:"riskAssessment"`
}

type ApproveRegistrationInput struct {
	RequestID string      `json:"requestId"`
	Tier      *TenantTier `json:"tier,omitempty"`
}

type AuditLog struct {
	ID           string            `json:"id"`
	Timestamp    time.Time         `json:"timestamp"`
	Action       AuditAction       `json:"action"`
	ResourceType AuditResourceType `json:"resourceType"`
	ResourceID   string            `json:"resourceId"`
	ResourceName *string           `json:"resourceName,omitempty"`
	ActorID      string            `json:"actorId"`
	ActorEmail   *string           `json:"actorEmail,omitempty"`
	ActorType    string            `json:"actorType"`
	IPAddress    *string           `json:"ipAddress,omitempty"`
	UserAgent    *string           `json:"userAgent,omitempty"`
	Details      map[string]any    `json:"details,omitempty"`
	OldValue     map[string]any    `json:"oldValue,omitempty"`
	NewValue     map[string]any    `json:"newValue,omitempty"`
	Status       string            `json:"status"`
	ErrorMessage *string           `json:"errorMessage,omitempty"`
}

type AuditLogConnection struct {
	Items      []AuditLog `json:"items"`
	TotalCount int        `json:"totalCount"`
	HasMore    bool       `json:"hasMore"`
}

type AuditLogFilter struct {
	ResourceType *AuditResourceType `json:"resourceType,omitempty"`
	ResourceID   *string            `json:"resourceId,omitempty"`
	Action       *AuditAction       `json:"action,omitempty"`
	ActorID      *string            `json:"actorId,omitempty"`
	StartTime    *time.Time         `json:"startTime,omitempty"`
	EndTime      *time.Time         `json:"endTime,omitempty"`
}

type AuthPayload struct {
	Token     string    `json:"token"`
	User      *User     `json:"user"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type BudgetAlert struct {
	ID              string      `json:"id"`
	Name            string      `json:"name"`
	Type            AlertType   `json:"type"`
	Threshold       float64     `json:"threshold"`
	ThresholdType   string      `json:"thresholdType"`
	Period          AlertPeriod `json:"period"`
	Enabled         bool        `json:"enabled"`
	LastTriggeredAt *time.Time  `json:"lastTriggeredAt,omitempty"`
	CreatedAt       time.Time   `json:"createdAt"`
}

type BudgetPolicy struct {
	Enabled           bool                 `json:"enabled"`
	DailyLimitUsd     float64              `json:"dailyLimitUSD"`
	WeeklyLimitUsd    float64              `json:"weeklyLimitUSD"`
	MonthlyLimitUsd   float64              `json:"monthlyLimitUSD"`
	MaxCostPerRequest float64              `json:"maxCostPerRequest"`
	AlertThreshold    float64              `json:"alertThreshold"`
	CriticalThreshold float64              `json:"criticalThreshold"`
	AlertWebhook      string               `json:"alertWebhook"`
	AlertEmails       []string             `json:"alertEmails"`
	AlertSlack        string               `json:"alertSlack"`
	OnExceeded        BudgetExceededAction `json:"onExceeded"`
	SoftLimitEnabled  bool                 `json:"softLimitEnabled"`
	SoftLimitBuffer   float64              `json:"softLimitBuffer"`
}

type BudgetPolicyInput struct {
	Enabled           *bool                 `json:"enabled,omitempty"`
	DailyLimitUsd     *float64              `json:"dailyLimitUSD,omitempty"`
	WeeklyLimitUsd    *float64              `json:"weeklyLimitUSD,omitempty"`
	MonthlyLimitUsd   *float64              `json:"monthlyLimitUSD,omitempty"`
	MaxCostPerRequest *float64              `json:"maxCostPerRequest,omitempty"`
	AlertThreshold    *float64              `json:"alertThreshold,omitempty"`
	CriticalThreshold *float64              `json:"criticalThreshold,omitempty"`
	AlertWebhook      *string               `json:"alertWebhook,omitempty"`
	AlertEmails       []string              `json:"alertEmails,omitempty"`
	AlertSlack        *string               `json:"alertSlack,omitempty"`
	OnExceeded        *BudgetExceededAction `json:"onExceeded,omitempty"`
	SoftLimitEnabled  *bool                 `json:"softLimitEnabled,omitempty"`
	SoftLimitBuffer   *float64              `json:"softLimitBuffer,omitempty"`
}

type CacheMetrics struct {
	Hits         int     `json:"hits"`
	Misses       int     `json:"misses"`
	HitRate      float64 `json:"hitRate"`
	TokensSaved  int     `json:"tokensSaved"`
	CostSaved    float64 `json:"costSaved"`
	AvgLatencyMs float64 `json:"avgLatencyMs"`
	Entries      int     `json:"entries"`
}

type CachingPolicy struct {
	Enabled             bool     `json:"enabled"`
	SimilarityThreshold float64  `json:"similarityThreshold"`
	TTLSeconds          int      `json:"ttlSeconds"`
	MaxCacheSize        int      `json:"maxCacheSize"`
	CacheStreaming      bool     `json:"cacheStreaming"`
	CacheToolCalls      bool     `json:"cacheToolCalls"`
	ExcludedModels      []string `json:"excludedModels"`
	ExcludedPatterns    []string `json:"excludedPatterns"`
	TrackSavings        bool     `json:"trackSavings"`
}

type CachingPolicyInput struct {
	Enabled             *bool    `json:"enabled,omitempty"`
	SimilarityThreshold *float64 `json:"similarityThreshold,omitempty"`
	TTLSeconds          *int     `json:"ttlSeconds,omitempty"`
	MaxCacheSize        *int     `json:"maxCacheSize,omitempty"`
	CacheStreaming      *bool    `json:"cacheStreaming,omitempty"`
	CacheToolCalls      *bool    `json:"cacheToolCalls,omitempty"`
	ExcludedModels      []string `json:"excludedModels,omitempty"`
	ExcludedPatterns    []string `json:"excludedPatterns,omitempty"`
	TrackSavings        *bool    `json:"trackSavings,omitempty"`
}

type CapabilityRoutingConfig struct {
	TaskModels []TaskModelMapping `json:"taskModels"`
}

type CapabilityRoutingConfigInput struct {
	TaskModels []TaskModelMappingInput `json:"taskModels,omitempty"`
}

type CircuitBreakerInfo struct {
	Provider string `json:"provider"`
	State    string `json:"state"`
	Failures int    `json:"failures"`
}

type ConnectionSettings struct {
	MaxConnections     int  `json:"maxConnections"`
	MaxIdleConnections int  `json:"maxIdleConnections"`
	IdleTimeoutSec     int  `json:"idleTimeoutSec"`
	RequestTimeoutSec  int  `json:"requestTimeoutSec"`
	EnableHTTP2        bool `json:"enableHTTP2"`
	EnableKeepAlive    bool `json:"enableKeepAlive"`
}

type ConnectionSettingsInput struct {
	MaxConnections     *int  `json:"maxConnections,omitempty"`
	MaxIdleConnections *int  `json:"maxIdleConnections,omitempty"`
	IdleTimeoutSec     *int  `json:"idleTimeoutSec,omitempty"`
	RequestTimeoutSec  *int  `json:"requestTimeoutSec,omitempty"`
	EnableHTTP2        *bool `json:"enableHTTP2,omitempty"`
	EnableKeepAlive    *bool `json:"enableKeepAlive,omitempty"`
}

type ContentFilteringConfig struct {
	Enabled               bool            `json:"enabled"`
	BlockedCategories     []string        `json:"blockedCategories"`
	CustomBlockedPatterns []string        `json:"customBlockedPatterns"`
	CustomAllowedPatterns []string        `json:"customAllowedPatterns"`
	OnDetection           DetectionAction `json:"onDetection"`
}

type ContentFilteringInput struct {
	Enabled               *bool            `json:"enabled,omitempty"`
	BlockedCategories     []string         `json:"blockedCategories,omitempty"`
	CustomBlockedPatterns []string         `json:"customBlockedPatterns,omitempty"`
	CustomAllowedPatterns []string         `json:"customAllowedPatterns,omitempty"`
	OnDetection           *DetectionAction `json:"onDetection,omitempty"`
}

type CostAnalysis struct {
	TotalCost            float64        `json:"totalCost"`
	PeriodStart          time.Time      `json:"periodStart"`
	PeriodEnd            time.Time      `json:"periodEnd"`
	DailyCosts           []DailyCost    `json:"dailyCosts"`
	CostByProvider       []ProviderCost `json:"costByProvider"`
	CostByModel          []ModelCost    `json:"costByModel"`
	ProjectedMonthlyCost float64        `json:"projectedMonthlyCost"`
	BudgetUtilization    float64        `json:"budgetUtilization"`
}

type CostRoutingConfig struct {
	SimpleQueryThreshold  float64  `json:"simpleQueryThreshold"`
	ComplexQueryThreshold float64  `json:"complexQueryThreshold"`
	SimpleModels          []string `json:"simpleModels"`
	MediumModels          []string `json:"mediumModels"`
	ComplexModels         []string `json:"complexModels"`
}

type CostRoutingConfigInput struct {
	SimpleQueryThreshold  *float64 `json:"simpleQueryThreshold,omitempty"`
	ComplexQueryThreshold *float64 `json:"complexQueryThreshold,omitempty"`
	SimpleModels          []string `json:"simpleModels,omitempty"`
	MediumModels          []string `json:"mediumModels,omitempty"`
	ComplexModels         []string `json:"complexModels,omitempty"`
}

type CreateAPIKeyInput struct {
	Name      string     `json:"name"`
	RoleID    *string    `json:"roleId,omitempty"`
	GroupID   *string    `json:"groupId,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

type CreateBudgetAlertInput struct {
	Name          string      `json:"name"`
	Type          AlertType   `json:"type"`
	Threshold     float64     `json:"threshold"`
	ThresholdType string      `json:"thresholdType"`
	Period        AlertPeriod `json:"period"`
	Enabled       *bool       `json:"enabled,omitempty"`
}

type CreateGroupInput struct {
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	RoleIds     []string `json:"roleIds"`
}

type CreateMCPServerInput struct {
	Name                string              `json:"name"`
	Description         *string             `json:"description,omitempty"`
	ServerType          MCPServerType       `json:"serverType"`
	Endpoint            string              `json:"endpoint"`
	Arguments           []string            `json:"arguments,omitempty"`
	Environment         map[string]any      `json:"environment,omitempty"`
	AuthType            MCPAuthType         `json:"authType"`
	AuthConfig          *MCPAuthConfigInput `json:"authConfig,omitempty"`
	Tags                []string            `json:"tags,omitempty"`
	AutoSync            *bool               `json:"autoSync,omitempty"`
	SyncIntervalMinutes *int                `json:"syncIntervalMinutes,omitempty"`
}

type CreateRegistrationRequestInput struct {
	OrganizationName  string      `json:"organizationName"`
	OrganizationEmail string      `json:"organizationEmail"`
	AdminName         string      `json:"adminName"`
	AdminEmail        string      `json:"adminEmail"`
	AdminPassword     string      `json:"adminPassword"`
	PreferredTier     *TenantTier `json:"preferredTier,omitempty"`
}

type CreateRoleInput struct {
	Name        string           `json:"name"`
	Description *string          `json:"description,omitempty"`
	IsDefault   *bool            `json:"isDefault,omitempty"`
	Policy      *RolePolicyInput `json:"policy,omitempty"`
}

type CreateTenantInput struct {
	Name               string           `json:"name"`
	Slug               *string          `json:"slug,omitempty"`
	Email              string           `json:"email"`
	Tier               *TenantTier      `json:"tier,omitempty"`
	AdminName          *string          `json:"adminName,omitempty"`
	AdminEmail         *string          `json:"adminEmail,omitempty"`
	AdminPassword      *string          `json:"adminPassword,omitempty"`
	PlanLimitsOverride *PlanLimitsInput `json:"planLimitsOverride,omitempty"`
}

type DailyCost struct {
	Date string  `json:"date"`
	Cost float64 `json:"cost"`
}

type DashboardStats struct {
	TotalRequests     int             `json:"totalRequests"`
	TotalTokens       int             `json:"totalTokens"`
	TotalCostUsd      float64         `json:"totalCostUSD"`
	AvgLatencyMs      float64         `json:"avgLatencyMs"`
	ErrorRate         float64         `json:"errorRate"`
	RequestsByHour    []HourlyStats   `json:"requestsByHour"`
	CostTrend         []DailyCost     `json:"costTrend"`
	TopModels         []ModelUsage    `json:"topModels"`
	ProviderBreakdown []ProviderUsage `json:"providerBreakdown"`
	APIKeyBreakdown   []APIKeyUsage   `json:"apiKeyBreakdown"`
}

type DiscoveredTool struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	SchemaHash  string         `json:"schemaHash"`
	Parameters  map[string]any `json:"parameters"`
	Category    *string        `json:"category,omitempty"`
	FirstSeenAt time.Time      `json:"firstSeenAt"`
	LastSeenAt  time.Time      `json:"lastSeenAt"`
	FirstSeenBy *string        `json:"firstSeenBy,omitempty"`
	SeenCount   int            `json:"seenCount"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type DiscoveredToolConnection struct {
	Items      []DiscoveredTool `json:"items"`
	TotalCount int              `json:"totalCount"`
	HasMore    bool             `json:"hasMore"`
}

type DiscoveredToolFilter struct {
	Name     *string               `json:"name,omitempty"`
	Category *string               `json:"category,omitempty"`
	Status   *ToolPermissionStatus `json:"status,omitempty"`
	RoleID   *string               `json:"roleId,omitempty"`
}

type FallbackConfig struct {
	Provider  string `json:"provider"`
	Model     string `json:"model"`
	Priority  int    `json:"priority"`
	TimeoutMs int    `json:"timeoutMs"`
}

type FallbackConfigInput struct {
	Provider  string `json:"provider"`
	Model     string `json:"model"`
	Priority  int    `json:"priority"`
	TimeoutMs *int   `json:"timeoutMs,omitempty"`
}

type Group struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	Description    *string   `json:"description,omitempty"`
	Roles          []Role    `json:"roles"`
	CreatedBy      *string   `json:"createdBy,omitempty"`
	CreatedByEmail *string   `json:"createdByEmail,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type HourlyStats struct {
	Hour     string `json:"hour"`
	Requests int    `json:"requests"`
	Tokens   int    `json:"tokens"`
}

type InjectionDetectionConfig struct {
	Enabled          bool                    `json:"enabled"`
	DetectionMethod  DetectionMethod         `json:"detectionMethod"`
	Sensitivity      DetectionSensitivity    `json:"sensitivity"`
	OnDetection      DetectionAction         `json:"onDetection"`
	BlockThreshold   float64                 `json:"blockThreshold"`
	PatternDetection *PatternDetectionConfig `json:"patternDetection"`
	MlDetection      *MLDetectionConfig      `json:"mlDetection"`
}

type InjectionDetectionInput struct {
	Enabled          *bool                  `json:"enabled,omitempty"`
	DetectionMethod  *DetectionMethod       `json:"detectionMethod,omitempty"`
	Sensitivity      *DetectionSensitivity  `json:"sensitivity,omitempty"`
	OnDetection      *DetectionAction       `json:"onDetection,omitempty"`
	BlockThreshold   *float64               `json:"blockThreshold,omitempty"`
	PatternDetection *PatternDetectionInput `json:"patternDetection,omitempty"`
	MlDetection      *MLDetectionInput      `json:"mlDetection,omitempty"`
}

type InputBoundsConfig struct {
	Enabled             bool    `json:"enabled"`
	MaxPromptLength     int     `json:"maxPromptLength"`
	MaxPromptTokens     int     `json:"maxPromptTokens"`
	MaxMessageCount     int     `json:"maxMessageCount"`
	MaxMessageLength    int     `json:"maxMessageLength"`
	MaxJSONNestingDepth int     `json:"maxJSONNestingDepth"`
	MaxURLCount         int     `json:"maxURLCount"`
	MaxAttachmentCount  int     `json:"maxAttachmentCount"`
	MaxAttachmentSize   int     `json:"maxAttachmentSize"`
	MaxRepeatedPhrases  int     `json:"maxRepeatedPhrases"`
	AnomalyThreshold    float64 `json:"anomalyThreshold"`
}

type InputBoundsInput struct {
	Enabled             *bool    `json:"enabled,omitempty"`
	MaxPromptLength     *int     `json:"maxPromptLength,omitempty"`
	MaxPromptTokens     *int     `json:"maxPromptTokens,omitempty"`
	MaxMessageCount     *int     `json:"maxMessageCount,omitempty"`
	MaxMessageLength    *int     `json:"maxMessageLength,omitempty"`
	MaxJSONNestingDepth *int     `json:"maxJSONNestingDepth,omitempty"`
	MaxURLCount         *int     `json:"maxURLCount,omitempty"`
	MaxAttachmentCount  *int     `json:"maxAttachmentCount,omitempty"`
	MaxAttachmentSize   *int     `json:"maxAttachmentSize,omitempty"`
	MaxRepeatedPhrases  *int     `json:"maxRepeatedPhrases,omitempty"`
	AnomalyThreshold    *float64 `json:"anomalyThreshold,omitempty"`
}

type LatencyRoutingConfig struct {
	MaxLatencyMs    int      `json:"maxLatencyMs"`
	PreferredModels []string `json:"preferredModels"`
}

type LatencyRoutingConfigInput struct {
	MaxLatencyMs    *int     `json:"maxLatencyMs,omitempty"`
	PreferredModels []string `json:"preferredModels,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MCPAuthConfigInput struct {
	APIKey       *string  `json:"apiKey,omitempty"`
	APIKeyHeader *string  `json:"apiKeyHeader,omitempty"`
	BearerToken  *string  `json:"bearerToken,omitempty"`
	ClientID     *string  `json:"clientId,omitempty"`
	ClientSecret *string  `json:"clientSecret,omitempty"`
	TokenURL     *string  `json:"tokenUrl,omitempty"`
	Scopes       []string `json:"scopes,omitempty"`
	Username     *string  `json:"username,omitempty"`
	Password     *string  `json:"password,omitempty"`
	ClientCert   *string  `json:"clientCert,omitempty"`
	ClientKey    *string  `json:"clientKey,omitempty"`
	CaCert       *string  `json:"caCert,omitempty"`
	AWSRegion    *string  `json:"awsRegion,omitempty"`
	AWSRoleArn   *string  `json:"awsRoleArn,omitempty"`
}

type MCPPolicies struct {
	Enabled            bool `json:"enabled"`
	AllowToolSearch    bool `json:"allowToolSearch"`
	AuditToolExecution bool `json:"auditToolExecution"`
}

type MCPPoliciesInput struct {
	Enabled            *bool `json:"enabled,omitempty"`
	AllowToolSearch    *bool `json:"allowToolSearch,omitempty"`
	AuditToolExecution *bool `json:"auditToolExecution,omitempty"`
}

type MCPSchemaChange struct {
	Type     MCPChangeType  `json:"type"`
	ToolName string         `json:"toolName"`
	Field    *string        `json:"field,omitempty"`
	OldValue map[string]any `json:"oldValue,omitempty"`
	NewValue map[string]any `json:"newValue,omitempty"`
	Breaking bool           `json:"breaking"`
}

type MCPServer struct {
	ID                  string             `json:"id"`
	Name                string             `json:"name"`
	Description         *string            `json:"description,omitempty"`
	ServerType          MCPServerType      `json:"serverType"`
	Endpoint            string             `json:"endpoint"`
	AuthType            MCPAuthType        `json:"authType"`
	Version             *string            `json:"version,omitempty"`
	Status              MCPServerStatus    `json:"status"`
	LastHealthCheck     *time.Time         `json:"lastHealthCheck,omitempty"`
	LastSyncAt          *time.Time         `json:"lastSyncAt,omitempty"`
	ErrorMessage        *string            `json:"errorMessage,omitempty"`
	ToolCount           int                `json:"toolCount"`
	Tags                []string           `json:"tags,omitempty"`
	AutoSync            bool               `json:"autoSync"`
	SyncIntervalMinutes int                `json:"syncIntervalMinutes"`
	CreatedAt           time.Time          `json:"createdAt"`
	UpdatedAt           time.Time          `json:"updatedAt"`
	CreatedBy           *string            `json:"createdBy,omitempty"`
	Tools               []MCPTool          `json:"tools"`
	Versions            []MCPServerVersion `json:"versions"`
}

type MCPServerToolStats struct {
	TotalTools   int `json:"totalTools"`
	AllowedCount int `json:"allowedCount"`
	SearchCount  int `json:"searchCount"`
	DeniedCount  int `json:"deniedCount"`
}

type MCPServerVersion struct {
	ID                 string            `json:"id"`
	ServerID           string            `json:"serverId"`
	Version            string            `json:"version"`
	CommitHash         *string           `json:"commitHash,omitempty"`
	ToolCount          int               `json:"toolCount"`
	Changes            []MCPSchemaChange `json:"changes"`
	ChangesSummary     *string           `json:"changesSummary,omitempty"`
	HasBreakingChanges bool              `json:"hasBreakingChanges"`
	CreatedAt          time.Time         `json:"createdAt"`
	CreatedBy          *string           `json:"createdBy,omitempty"`
}

type MCPServerWithTools struct {
	Server *MCPServer              `json:"server"`
	Tools  []MCPToolWithVisibility `json:"tools"`
	Stats  *MCPServerToolStats     `json:"stats"`
}

type MCPTool struct {
	ID                 string            `json:"id"`
	ServerID           string            `json:"serverId"`
	ServerName         string            `json:"serverName"`
	Name               string            `json:"name"`
	Description        *string           `json:"description,omitempty"`
	Category           *string           `json:"category,omitempty"`
	InputSchema        map[string]any    `json:"inputSchema"`
	InputExamples      []map[string]any  `json:"inputExamples,omitempty"`
	DeferLoading       bool              `json:"deferLoading"`
	IsDeprecated       bool              `json:"isDeprecated"`
	DeprecationMessage *string           `json:"deprecationMessage,omitempty"`
	ExecutionCount     int               `json:"executionCount"`
	AvgExecutionTimeMs *int              `json:"avgExecutionTimeMs,omitempty"`
	CreatedAt          time.Time         `json:"createdAt"`
	UpdatedAt          time.Time         `json:"updatedAt"`
	Visibility         MCPToolVisibility `json:"visibility"`
}

type MCPToolExecution struct {
	ID           string         `json:"id"`
	ServerID     string         `json:"serverId"`
	ToolID       string         `json:"toolId"`
	RoleID       *string        `json:"roleId,omitempty"`
	RequestID    *string        `json:"requestId,omitempty"`
	InputParams  map[string]any `json:"inputParams,omitempty"`
	OutputResult map[string]any `json:"outputResult,omitempty"`
	Status       string         `json:"status"`
	ErrorMessage *string        `json:"errorMessage,omitempty"`
	StartedAt    time.Time      `json:"startedAt"`
	CompletedAt  *time.Time     `json:"completedAt,omitempty"`
	DurationMs   *int           `json:"durationMs,omitempty"`
}

type MCPToolPermission struct {
	ID             string            `json:"id"`
	RoleID         string            `json:"roleId"`
	ServerID       string            `json:"serverId"`
	ToolID         string            `json:"toolId"`
	Visibility     MCPToolVisibility `json:"visibility"`
	DecidedBy      *string           `json:"decidedBy,omitempty"`
	DecidedByEmail *string           `json:"decidedByEmail,omitempty"`
	DecidedAt      *time.Time        `json:"decidedAt,omitempty"`
	DecisionReason *string           `json:"decisionReason,omitempty"`
}

type MCPToolWithVisibility struct {
	Tool       *MCPTool          `json:"tool"`
	Visibility MCPToolVisibility `json:"visibility"`
	DecidedBy  *string           `json:"decidedBy,omitempty"`
	DecidedAt  *time.Time        `json:"decidedAt,omitempty"`
}

type MLDetectionConfig struct {
	Enabled            bool    `json:"enabled"`
	Model              string  `json:"model"`
	CustomEndpoint     string  `json:"customEndpoint"`
	InjectionThreshold float64 `json:"injectionThreshold"`
	JailbreakThreshold float64 `json:"jailbreakThreshold"`
}

type MLDetectionInput struct {
	Enabled            *bool    `json:"enabled,omitempty"`
	Model              *string  `json:"model,omitempty"`
	CustomEndpoint     *string  `json:"customEndpoint,omitempty"`
	CustomAPIKey       *string  `json:"customAPIKey,omitempty"`
	InjectionThreshold *float64 `json:"injectionThreshold,omitempty"`
	JailbreakThreshold *float64 `json:"jailbreakThreshold,omitempty"`
}

type Model struct {
	ID                string   `json:"id"`
	Name              string   `json:"name"`
	Provider          Provider `json:"provider"`
	Enabled           bool     `json:"enabled"`
	SupportsTools     bool     `json:"supportsTools"`
	SupportsStreaming bool     `json:"supportsStreaming"`
	ContextLimit      int      `json:"contextLimit"`
	InputCostPer1m    float64  `json:"inputCostPer1M"`
	OutputCostPer1m   float64  `json:"outputCostPer1M"`
}

type ModelCost struct {
	Model    string  `json:"model"`
	Cost     float64 `json:"cost"`
	Requests int     `json:"requests"`
}

type ModelPerformance struct {
	Model        string  `json:"model"`
	AvgLatencyMs float64 `json:"avgLatencyMs"`
	SuccessRate  float64 `json:"successRate"`
	RequestCount int     `json:"requestCount"`
}

type ModelRateLimit struct {
	ModelID           string  `json:"modelId"`
	RequestsPerMinute int     `json:"requestsPerMinute"`
	TokensPerMinute   int     `json:"tokensPerMinute"`
	CostPerDayUsd     float64 `json:"costPerDayUSD"`
}

type ModelRateLimitInput struct {
	ModelID           string   `json:"modelId"`
	RequestsPerMinute *int     `json:"requestsPerMinute,omitempty"`
	TokensPerMinute   *int     `json:"tokensPerMinute,omitempty"`
	CostPerDayUsd     *float64 `json:"costPerDayUSD,omitempty"`
}

type ModelRestrictions struct {
	AllowedModels       []string   `json:"allowedModels"`
	AllowedProviders    []Provider `json:"allowedProviders"`
	DefaultModel        string     `json:"defaultModel"`
	MaxTokensPerRequest int        `json:"maxTokensPerRequest"`
}

type ModelRestrictionsInput struct {
	AllowedModels       []string   `json:"allowedModels,omitempty"`
	AllowedProviders    []Provider `json:"allowedProviders,omitempty"`
	DefaultModel        *string    `json:"defaultModel,omitempty"`
	MaxTokensPerRequest *int       `json:"maxTokensPerRequest,omitempty"`
}

type ModelSwitch struct {
	FromModel string `json:"fromModel"`
	ToModel   string `json:"toModel"`
	Count     int    `json:"count"`
}

type ModelTokenBreakdown struct {
	Model          string  `json:"model"`
	InputTokens    int     `json:"inputTokens"`
	OutputTokens   int     `json:"outputTokens"`
	ThinkingTokens int     `json:"thinkingTokens"`
	CostUsd        float64 `json:"costUsd"`
}

type ModelUsage struct {
	Model    string  `json:"model"`
	Requests int     `json:"requests"`
	Tokens   int     `json:"tokens"`
	Cost     float64 `json:"cost"`
}

type Mutation struct {
}

type NormalizationConfig struct {
	Enabled                  bool            `json:"enabled"`
	UnicodeNormalization     UnicodeNormForm `json:"unicodeNormalization"`
	NormalizeNewlines        bool            `json:"normalizeNewlines"`
	StripNullBytes           bool            `json:"stripNullBytes"`
	RemoveInvisibleChars     bool            `json:"removeInvisibleChars"`
	DetectMixedEncodings     bool            `json:"detectMixedEncodings"`
	DecodeBase64             bool            `json:"decodeBase64"`
	DecodeURLEncoding        bool            `json:"decodeURLEncoding"`
	RejectSuspiciousEncoding bool            `json:"rejectSuspiciousEncoding"`
	CollapseWhitespace       bool            `json:"collapseWhitespace"`
	TrimWhitespace           bool            `json:"trimWhitespace"`
}

type NormalizationInput struct {
	Enabled                  *bool            `json:"enabled,omitempty"`
	UnicodeNormalization     *UnicodeNormForm `json:"unicodeNormalization,omitempty"`
	NormalizeNewlines        *bool            `json:"normalizeNewlines,omitempty"`
	StripNullBytes           *bool            `json:"stripNullBytes,omitempty"`
	RemoveInvisibleChars     *bool            `json:"removeInvisibleChars,omitempty"`
	DetectMixedEncodings     *bool            `json:"detectMixedEncodings,omitempty"`
	DecodeBase64             *bool            `json:"decodeBase64,omitempty"`
	DecodeURLEncoding        *bool            `json:"decodeURLEncoding,omitempty"`
	RejectSuspiciousEncoding *bool            `json:"rejectSuspiciousEncoding,omitempty"`
	CollapseWhitespace       *bool            `json:"collapseWhitespace,omitempty"`
	TrimWhitespace           *bool            `json:"trimWhitespace,omitempty"`
}

type OutputValidationConfig struct {
	Enabled                   bool                  `json:"enabled"`
	EnforceSchema             bool                  `json:"enforceSchema"`
	OutputSchema              string                `json:"outputSchema"`
	RejectInvalidSchema       bool                  `json:"rejectInvalidSchema"`
	DetectCodeExecution       bool                  `json:"detectCodeExecution"`
	DetectSQLStatements       bool                  `json:"detectSQLStatements"`
	DetectShellCommands       bool                  `json:"detectShellCommands"`
	DetectHTMLScripts         bool                  `json:"detectHTMLScripts"`
	EscapeForHTML             bool                  `json:"escapeForHTML"`
	EscapeForSQL              bool                  `json:"escapeForSQL"`
	EscapeForCli              bool                  `json:"escapeForCLI"`
	DetectSecretLeakage       bool                  `json:"detectSecretLeakage"`
	SecretPatterns            []string              `json:"secretPatterns"`
	DetectPIILeakage          bool                  `json:"detectPIILeakage"`
	DetectSystemPromptLeakage bool                  `json:"detectSystemPromptLeakage"`
	ApplyContentFiltering     bool                  `json:"applyContentFiltering"`
	OnViolation               OutputViolationAction `json:"onViolation"`
}

type OutputValidationInput struct {
	Enabled                   *bool                  `json:"enabled,omitempty"`
	EnforceSchema             *bool                  `json:"enforceSchema,omitempty"`
	OutputSchema              *string                `json:"outputSchema,omitempty"`
	RejectInvalidSchema       *bool                  `json:"rejectInvalidSchema,omitempty"`
	DetectCodeExecution       *bool                  `json:"detectCodeExecution,omitempty"`
	DetectSQLStatements       *bool                  `json:"detectSQLStatements,omitempty"`
	DetectShellCommands       *bool                  `json:"detectShellCommands,omitempty"`
	DetectHTMLScripts         *bool                  `json:"detectHTMLScripts,omitempty"`
	EscapeForHTML             *bool                  `json:"escapeForHTML,omitempty"`
	EscapeForSQL              *bool                  `json:"escapeForSQL,omitempty"`
	EscapeForCli              *bool                  `json:"escapeForCLI,omitempty"`
	DetectSecretLeakage       *bool                  `json:"detectSecretLeakage,omitempty"`
	SecretPatterns            []string               `json:"secretPatterns,omitempty"`
	DetectPIILeakage          *bool                  `json:"detectPIILeakage,omitempty"`
	DetectSystemPromptLeakage *bool                  `json:"detectSystemPromptLeakage,omitempty"`
	ApplyContentFiltering     *bool                  `json:"applyContentFiltering,omitempty"`
	OnViolation               *OutputViolationAction `json:"onViolation,omitempty"`
}

type PIIPolicyConfig struct {
	Enabled       bool                `json:"enabled"`
	ScanInputs    bool                `json:"scanInputs"`
	ScanOutputs   bool                `json:"scanOutputs"`
	ScanRetrieved bool                `json:"scanRetrieved"`
	Categories    []string            `json:"categories"`
	OnDetection   PIIAction           `json:"onDetection"`
	Redaction     *PIIRedactionConfig `json:"redaction"`
}

type PIIPolicyInput struct {
	Enabled       *bool              `json:"enabled,omitempty"`
	ScanInputs    *bool              `json:"scanInputs,omitempty"`
	ScanOutputs   *bool              `json:"scanOutputs,omitempty"`
	ScanRetrieved *bool              `json:"scanRetrieved,omitempty"`
	Categories    []string           `json:"categories,omitempty"`
	OnDetection   *PIIAction         `json:"onDetection,omitempty"`
	Redaction     *PIIRedactionInput `json:"redaction,omitempty"`
}

type PIIRedactionConfig struct {
	PlaceholderFormat      string `json:"placeholderFormat"`
	StoreOriginals         bool   `json:"storeOriginals"`
	RestoreInResponse      bool   `json:"restoreInResponse"`
	ConsistentPlaceholders bool   `json:"consistentPlaceholders"`
}

type PIIRedactionInput struct {
	PlaceholderFormat      *string `json:"placeholderFormat,omitempty"`
	StoreOriginals         *bool   `json:"storeOriginals,omitempty"`
	RestoreInResponse      *bool   `json:"restoreInResponse,omitempty"`
	ConsistentPlaceholders *bool   `json:"consistentPlaceholders,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PatternDetectionConfig struct {
	Enabled                    bool                 `json:"enabled"`
	DetectIgnoreInstructions   bool                 `json:"detectIgnoreInstructions"`
	DetectSystemPromptRequests bool                 `json:"detectSystemPromptRequests"`
	DetectRoleConfusion        bool                 `json:"detectRoleConfusion"`
	DetectJailbreakPhrases     bool                 `json:"detectJailbreakPhrases"`
	DetectToolCoercion         bool                 `json:"detectToolCoercion"`
	DetectEncodingEvasion      bool                 `json:"detectEncodingEvasion"`
	CustomBlockPatterns        []string             `json:"customBlockPatterns"`
	CustomWarnPatterns         []string             `json:"customWarnPatterns"`
	EnableFuzzyMatching        bool                 `json:"enableFuzzyMatching"`
	EnableWordMatching         bool                 `json:"enableWordMatching"`
	EnableNormalization        bool                 `json:"enableNormalization"`
	FuzzyThreshold             float64              `json:"fuzzyThreshold"`
	Sensitivity                DetectionSensitivity `json:"sensitivity"`
	WhitelistedPhrases         []string             `json:"whitelistedPhrases"`
}

type PatternDetectionInput struct {
	Enabled                    *bool                 `json:"enabled,omitempty"`
	DetectIgnoreInstructions   *bool                 `json:"detectIgnoreInstructions,omitempty"`
	DetectSystemPromptRequests *bool                 `json:"detectSystemPromptRequests,omitempty"`
	DetectRoleConfusion        *bool                 `json:"detectRoleConfusion,omitempty"`
	DetectJailbreakPhrases     *bool                 `json:"detectJailbreakPhrases,omitempty"`
	DetectToolCoercion         *bool                 `json:"detectToolCoercion,omitempty"`
	DetectEncodingEvasion      *bool                 `json:"detectEncodingEvasion,omitempty"`
	CustomBlockPatterns        []string              `json:"customBlockPatterns,omitempty"`
	CustomWarnPatterns         []string              `json:"customWarnPatterns,omitempty"`
	EnableFuzzyMatching        *bool                 `json:"enableFuzzyMatching,omitempty"`
	EnableWordMatching         *bool                 `json:"enableWordMatching,omitempty"`
	EnableNormalization        *bool                 `json:"enableNormalization,omitempty"`
	FuzzyThreshold             *float64              `json:"fuzzyThreshold,omitempty"`
	Sensitivity                *DetectionSensitivity `json:"sensitivity,omitempty"`
	WhitelistedPhrases         []string              `json:"whitelistedPhrases,omitempty"`
}

type PerformanceMetrics struct {
	AvgLatencyMs     float64            `json:"avgLatencyMs"`
	P50LatencyMs     float64            `json:"p50LatencyMs"`
	P95LatencyMs     float64            `json:"p95LatencyMs"`
	P99LatencyMs     float64            `json:"p99LatencyMs"`
	SuccessRate      float64            `json:"successRate"`
	ErrorRate        float64            `json:"errorRate"`
	ModelPerformance []ModelPerformance `json:"modelPerformance"`
}

type PlanLimits struct {
	MaxConnectionsPerProvider int `json:"maxConnectionsPerProvider"`
	MaxIdleConnections        int `json:"maxIdleConnections"`
	MaxConcurrentRequests     int `json:"maxConcurrentRequests"`
	MaxQueuedRequests         int `json:"maxQueuedRequests"`
	MaxRoles                  int `json:"maxRoles"`
	MaxAPIKeys                int `json:"maxAPIKeys"`
	MaxProviders              int `json:"maxProviders"`
}

type PlanLimitsInput struct {
	MaxConnectionsPerProvider *int `json:"maxConnectionsPerProvider,omitempty"`
	MaxIdleConnections        *int `json:"maxIdleConnections,omitempty"`
	MaxConcurrentRequests     *int `json:"maxConcurrentRequests,omitempty"`
	MaxQueuedRequests         *int `json:"maxQueuedRequests,omitempty"`
	MaxRoles                  *int `json:"maxRoles,omitempty"`
	MaxAPIKeys                *int `json:"maxAPIKeys,omitempty"`
	MaxProviders              *int `json:"maxProviders,omitempty"`
}

type PolicyViolationRecord struct {
	ID            string    `json:"id"`
	APIKeyID      *string   `json:"apiKeyId,omitempty"`
	PolicyID      string    `json:"policyId"`
	PolicyName    string    `json:"policyName"`
	ViolationType string    `json:"violationType"`
	Severity      int       `json:"severity"`
	Message       *string   `json:"message,omitempty"`
	Timestamp     time.Time `json:"timestamp"`
	Metadata      *string   `json:"metadata,omitempty"`
}

type PolicyViolationSummary struct {
	ViolationType string  `json:"violationType"`
	Count         int     `json:"count"`
	AvgSeverity   float64 `json:"avgSeverity"`
}

type PromptPolicies struct {
	StructuralSeparation       *StructuralSeparationConfig   `json:"structuralSeparation"`
	Normalization              *NormalizationConfig          `json:"normalization"`
	InputBounds                *InputBoundsConfig            `json:"inputBounds"`
	DirectInjectionDetection   *InjectionDetectionConfig     `json:"directInjectionDetection"`
	IndirectInjectionDetection *InjectionDetectionConfig     `json:"indirectInjectionDetection"`
	PiiPolicy                  *PIIPolicyConfig              `json:"piiPolicy"`
	ContentFiltering           *ContentFilteringConfig       `json:"contentFiltering"`
	SystemPromptProtection     *SystemPromptProtectionConfig `json:"systemPromptProtection"`
	OutputValidation           *OutputValidationConfig       `json:"outputValidation"`
}

type PromptPoliciesInput struct {
	StructuralSeparation       *StructuralSeparationInput   `json:"structuralSeparation,omitempty"`
	Normalization              *NormalizationInput          `json:"normalization,omitempty"`
	InputBounds                *InputBoundsInput            `json:"inputBounds,omitempty"`
	DirectInjectionDetection   *InjectionDetectionInput     `json:"directInjectionDetection,omitempty"`
	IndirectInjectionDetection *InjectionDetectionInput     `json:"indirectInjectionDetection,omitempty"`
	PiiPolicy                  *PIIPolicyInput              `json:"piiPolicy,omitempty"`
	ContentFiltering           *ContentFilteringInput       `json:"contentFiltering,omitempty"`
	SystemPromptProtection     *SystemPromptProtectionInput `json:"systemPromptProtection,omitempty"`
	OutputValidation           *OutputValidationInput       `json:"outputValidation,omitempty"`
}

type ProviderAPIKey struct {
	ID                 string     `json:"id"`
	Provider           Provider   `json:"provider"`
	Name               *string    `json:"name,omitempty"`
	KeyPrefix          string     `json:"keyPrefix"`
	CredentialType     string     `json:"credentialType"`
	Priority           int        `json:"priority"`
	Enabled            bool       `json:"enabled"`
	HealthScore        float64    `json:"healthScore"`
	SuccessCount       int        `json:"successCount"`
	FailureCount       int        `json:"failureCount"`
	RateLimitRemaining *int       `json:"rateLimitRemaining,omitempty"`
	RateLimitResetAt   *time.Time `json:"rateLimitResetAt,omitempty"`
	RequestCount       int        `json:"requestCount"`
	LastUsedAt         *time.Time `json:"lastUsedAt,omitempty"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
}

type ProviderConfig struct {
	Provider           Provider            `json:"provider"`
	Enabled            bool                `json:"enabled"`
	HasAPIKey          bool                `json:"hasApiKey"`
	HasAccessKeys      bool                `json:"hasAccessKeys"`
	StreamingMode      *string             `json:"streamingMode,omitempty"`
	BaseURL            *string             `json:"baseUrl,omitempty"`
	Region             *string             `json:"region,omitempty"`
	RegionPrefix       *string             `json:"regionPrefix,omitempty"`
	ResourceName       *string             `json:"resourceName,omitempty"`
	APIVersion         *string             `json:"apiVersion,omitempty"`
	ModelsURL          *string             `json:"modelsUrl,omitempty"`
	ConnectionSettings *ConnectionSettings `json:"connectionSettings"`
	PlanCeiling        *ConnectionSettings `json:"planCeiling"`
	APIKeys            []ProviderAPIKey    `json:"apiKeys"`
}

type ProviderCost struct {
	Provider   Provider `json:"provider"`
	Cost       float64  `json:"cost"`
	Percentage float64  `json:"percentage"`
}

type ProviderHealthInfo struct {
	Provider     string  `json:"provider"`
	Model        string  `json:"model"`
	HealthScore  float64 `json:"healthScore"`
	SuccessRate  float64 `json:"successRate"`
	P95LatencyMs float64 `json:"p95LatencyMs"`
	Requests     int     `json:"requests"`
}

type ProviderHealthMetrics struct {
	Providers []ProviderHealthInfo `json:"providers"`
}

type ProviderModelUsage struct {
	Provider     string  `json:"provider"`
	Model        string  `json:"model"`
	RequestCount int     `json:"requestCount"`
	TokenCount   int     `json:"tokenCount"`
	CostUsd      float64 `json:"costUsd"`
}

type ProviderUsage struct {
	Provider   Provider `json:"provider"`
	Requests   int      `json:"requests"`
	Percentage float64  `json:"percentage"`
}

type ProviderWeight struct {
	Provider string `json:"provider"`
	Weight   int    `json:"weight"`
}

type ProviderWeightInput struct {
	Provider string `json:"provider"`
	Weight   int    `json:"weight"`
}

type Query struct {
}

type RateLimitPolicy struct {
	RequestsPerMinute int              `json:"requestsPerMinute"`
	RequestsPerHour   int              `json:"requestsPerHour"`
	RequestsPerDay    int              `json:"requestsPerDay"`
	TokensPerMinute   int              `json:"tokensPerMinute"`
	TokensPerHour     int              `json:"tokensPerHour"`
	TokensPerDay      int              `json:"tokensPerDay"`
	CostPerMinuteUsd  float64          `json:"costPerMinuteUSD"`
	CostPerHourUsd    float64          `json:"costPerHourUSD"`
	CostPerDayUsd     float64          `json:"costPerDayUSD"`
	CostPerMonthUsd   float64          `json:"costPerMonthUSD"`
	BurstLimit        int              `json:"burstLimit"`
	BurstTokens       int              `json:"burstTokens"`
	PerModelLimits    []ModelRateLimit `json:"perModelLimits"`
}

type RateLimitPolicyInput struct {
	RequestsPerMinute *int                  `json:"requestsPerMinute,omitempty"`
	RequestsPerHour   *int                  `json:"requestsPerHour,omitempty"`
	RequestsPerDay    *int                  `json:"requestsPerDay,omitempty"`
	TokensPerMinute   *int                  `json:"tokensPerMinute,omitempty"`
	TokensPerHour     *int                  `json:"tokensPerHour,omitempty"`
	TokensPerDay      *int                  `json:"tokensPerDay,omitempty"`
	CostPerMinuteUsd  *float64              `json:"costPerMinuteUSD,omitempty"`
	CostPerHourUsd    *float64              `json:"costPerHourUSD,omitempty"`
	CostPerDayUsd     *float64              `json:"costPerDayUSD,omitempty"`
	CostPerMonthUsd   *float64              `json:"costPerMonthUSD,omitempty"`
	BurstLimit        *int                  `json:"burstLimit,omitempty"`
	BurstTokens       *int                  `json:"burstTokens,omitempty"`
	PerModelLimits    []ModelRateLimitInput `json:"perModelLimits,omitempty"`
}

type RefreshModelsResult struct {
	Success  bool     `json:"success"`
	Count    int      `json:"count"`
	Message  string   `json:"message"`
	Provider Provider `json:"provider"`
}

type RegistrationRequest struct {
	ID                string     `json:"id"`
	OrganizationName  string     `json:"organizationName"`
	OrganizationEmail string     `json:"organizationEmail"`
	AdminName         string     `json:"adminName"`
	AdminEmail        string     `json:"adminEmail"`
	Slug              string     `json:"slug"`
	Status            string     `json:"status"`
	RejectionReason   *string    `json:"rejectionReason,omitempty"`
	RequestedAt       time.Time  `json:"requestedAt"`
	ReviewedAt        *time.Time `json:"reviewedAt,omitempty"`
	ReviewedBy        *string    `json:"reviewedBy,omitempty"`
	CreatedAt         time.Time  `json:"createdAt"`
	UpdatedAt         time.Time  `json:"updatedAt"`
}

type RejectRegistrationInput struct {
	RequestID string `json:"requestId"`
	Reason    string `json:"reason"`
}

type RequestLog struct {
	ID           string    `json:"id"`
	Model        string    `json:"model"`
	Provider     Provider  `json:"provider"`
	Status       string    `json:"status"`
	InputTokens  int       `json:"inputTokens"`
	OutputTokens int       `json:"outputTokens"`
	LatencyMs    int       `json:"latencyMs"`
	CostUsd      float64   `json:"costUSD"`
	APIKeyName   *string   `json:"apiKeyName,omitempty"`
	ErrorCode    *string   `json:"errorCode,omitempty"`
	ErrorMessage *string   `json:"errorMessage,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
}

type RequestLogConnection struct {
	Edges      []RequestLog `json:"edges"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

type RequestLogDetail struct {
	ID           string         `json:"id"`
	Model        string         `json:"model"`
	Provider     Provider       `json:"provider"`
	Status       string         `json:"status"`
	InputTokens  int            `json:"inputTokens"`
	OutputTokens int            `json:"outputTokens"`
	LatencyMs    int            `json:"latencyMs"`
	CostUsd      float64        `json:"costUSD"`
	APIKeyName   *string        `json:"apiKeyName,omitempty"`
	ErrorCode    *string        `json:"errorCode,omitempty"`
	ErrorMessage *string        `json:"errorMessage,omitempty"`
	Prompt       *string        `json:"prompt,omitempty"`
	Response     *string        `json:"response,omitempty"`
	Metadata     map[string]any `json:"metadata,omitempty"`
	CreatedAt    time.Time      `json:"createdAt"`
}

type RequestLogFilter struct {
	Model     *string    `json:"model,omitempty"`
	Provider  *Provider  `json:"provider,omitempty"`
	Status    *string    `json:"status,omitempty"`
	APIKeyID  *string    `json:"apiKeyId,omitempty"`
	StartDate *time.Time `json:"startDate,omitempty"`
	EndDate   *time.Time `json:"endDate,omitempty"`
	Search    *string    `json:"search,omitempty"`
}

type ResilienceMetrics struct {
	CircuitBreakers     []CircuitBreakerInfo `json:"circuitBreakers"`
	RetryAttempts       int                  `json:"retryAttempts"`
	FallbackInvocations int                  `json:"fallbackInvocations"`
	FallbackSuccessRate float64              `json:"fallbackSuccessRate"`
}

type ResiliencePolicy struct {
	Enabled                 bool             `json:"enabled"`
	RetryEnabled            bool             `json:"retryEnabled"`
	MaxRetries              int              `json:"maxRetries"`
	RetryBackoffMs          int              `json:"retryBackoffMs"`
	RetryBackoffMax         int              `json:"retryBackoffMax"`
	RetryJitter             bool             `json:"retryJitter"`
	RetryOnTimeout          bool             `json:"retryOnTimeout"`
	RetryOnRateLimit        bool             `json:"retryOnRateLimit"`
	RetryOnServerError      bool             `json:"retryOnServerError"`
	RetryableErrors         []string         `json:"retryableErrors"`
	FallbackEnabled         bool             `json:"fallbackEnabled"`
	FallbackChain           []FallbackConfig `json:"fallbackChain"`
	CircuitBreakerEnabled   bool             `json:"circuitBreakerEnabled"`
	CircuitBreakerThreshold int              `json:"circuitBreakerThreshold"`
	CircuitBreakerTimeout   int              `json:"circuitBreakerTimeout"`
	RequestTimeoutMs        int              `json:"requestTimeoutMs"`
}

type ResiliencePolicyInput struct {
	Enabled                 *bool                 `json:"enabled,omitempty"`
	RetryEnabled            *bool                 `json:"retryEnabled,omitempty"`
	MaxRetries              *int                  `json:"maxRetries,omitempty"`
	RetryBackoffMs          *int                  `json:"retryBackoffMs,omitempty"`
	RetryBackoffMax         *int                  `json:"retryBackoffMax,omitempty"`
	RetryJitter             *bool                 `json:"retryJitter,omitempty"`
	RetryOnTimeout          *bool                 `json:"retryOnTimeout,omitempty"`
	RetryOnRateLimit        *bool                 `json:"retryOnRateLimit,omitempty"`
	RetryOnServerError      *bool                 `json:"retryOnServerError,omitempty"`
	RetryableErrors         []string              `json:"retryableErrors,omitempty"`
	FallbackEnabled         *bool                 `json:"fallbackEnabled,omitempty"`
	FallbackChain           []FallbackConfigInput `json:"fallbackChain,omitempty"`
	CircuitBreakerEnabled   *bool                 `json:"circuitBreakerEnabled,omitempty"`
	CircuitBreakerThreshold *int                  `json:"circuitBreakerThreshold,omitempty"`
	CircuitBreakerTimeout   *int                  `json:"circuitBreakerTimeout,omitempty"`
	RequestTimeoutMs        *int                  `json:"requestTimeoutMs,omitempty"`
}

type RiskAssessment struct {
	OverallRiskScore float64                  `json:"overallRiskScore"`
	RiskLevel        string                   `json:"riskLevel"`
	PolicyViolations []PolicyViolationSummary `json:"policyViolations"`
	RecentViolations []PolicyViolationRecord  `json:"recentViolations"`
	Recommendations  []string                 `json:"recommendations"`
}

type Role struct {
	ID             string      `json:"id"`
	Name           string      `json:"name"`
	Description    *string     `json:"description,omitempty"`
	IsDefault      bool        `json:"isDefault"`
	IsSystem       bool        `json:"isSystem"`
	Policy         *RolePolicy `json:"policy,omitempty"`
	CreatedBy      *string     `json:"createdBy,omitempty"`
	CreatedByEmail *string     `json:"createdByEmail,omitempty"`
	CreatedAt      time.Time   `json:"createdAt"`
	UpdatedAt      time.Time   `json:"updatedAt"`
}

type RolePolicy struct {
	ID                string             `json:"id"`
	RoleID            string             `json:"roleId"`
	PromptPolicies    *PromptPolicies    `json:"promptPolicies"`
	ToolPolicies      *ToolPolicies      `json:"toolPolicies"`
	RateLimitPolicy   *RateLimitPolicy   `json:"rateLimitPolicy"`
	ModelRestrictions *ModelRestrictions `json:"modelRestrictions"`
	CachingPolicy     *CachingPolicy     `json:"cachingPolicy"`
	RoutingPolicy     *RoutingPolicy     `json:"routingPolicy"`
	ResiliencePolicy  *ResiliencePolicy  `json:"resiliencePolicy"`
	BudgetPolicy      *BudgetPolicy      `json:"budgetPolicy"`
	McpPolicies       *MCPPolicies       `json:"mcpPolicies"`
	CreatedAt         time.Time          `json:"createdAt"`
	UpdatedAt         time.Time          `json:"updatedAt"`
}

type RolePolicyInput struct {
	PromptPolicies    *PromptPoliciesInput    `json:"promptPolicies,omitempty"`
	ToolPolicies      *ToolPoliciesInput      `json:"toolPolicies,omitempty"`
	RateLimitPolicy   *RateLimitPolicyInput   `json:"rateLimitPolicy,omitempty"`
	ModelRestrictions *ModelRestrictionsInput `json:"modelRestrictions,omitempty"`
	CachingPolicy     *CachingPolicyInput     `json:"cachingPolicy,omitempty"`
	RoutingPolicy     *RoutingPolicyInput     `json:"routingPolicy,omitempty"`
	ResiliencePolicy  *ResiliencePolicyInput  `json:"resiliencePolicy,omitempty"`
	BudgetPolicy      *BudgetPolicyInput      `json:"budgetPolicy,omitempty"`
	McpPolicies       *MCPPoliciesInput       `json:"mcpPolicies,omitempty"`
}

type RoutingMetrics struct {
	Decisions            int             `json:"decisions"`
	StrategyDistribution []StrategyCount `json:"strategyDistribution"`
	ModelSwitches        []ModelSwitch   `json:"modelSwitches"`
	Failures             int             `json:"failures"`
}

type RoutingPolicy struct {
	Enabled            bool                     `json:"enabled"`
	Strategy           RoutingStrategy          `json:"strategy"`
	CostConfig         *CostRoutingConfig       `json:"costConfig,omitempty"`
	LatencyConfig      *LatencyRoutingConfig    `json:"latencyConfig,omitempty"`
	WeightedConfig     *WeightedRoutingConfig   `json:"weightedConfig,omitempty"`
	CapabilityConfig   *CapabilityRoutingConfig `json:"capabilityConfig,omitempty"`
	AllowModelOverride bool                     `json:"allowModelOverride"`
}

type RoutingPolicyInput struct {
	Enabled            *bool                         `json:"enabled,omitempty"`
	Strategy           *RoutingStrategy              `json:"strategy,omitempty"`
	CostConfig         *CostRoutingConfigInput       `json:"costConfig,omitempty"`
	LatencyConfig      *LatencyRoutingConfigInput    `json:"latencyConfig,omitempty"`
	WeightedConfig     *WeightedRoutingConfigInput   `json:"weightedConfig,omitempty"`
	CapabilityConfig   *CapabilityRoutingConfigInput `json:"capabilityConfig,omitempty"`
	AllowModelOverride *bool                         `json:"allowModelOverride,omitempty"`
}

type SetMCPPermissionInput struct {
	RoleID     string            `json:"roleId"`
	ServerID   string            `json:"serverId"`
	ToolID     string            `json:"toolId"`
	Visibility MCPToolVisibility `json:"visibility"`
	Reason     *string           `json:"reason,omitempty"`
}

type SetToolPermissionInput struct {
	ToolID string               `json:"toolId"`
	RoleID string               `json:"roleId"`
	Status ToolPermissionStatus `json:"status"`
	Reason *string              `json:"reason,omitempty"`
}

type SetToolPermissionsBulkInput struct {
	RoleID      string                `json:"roleId"`
	Permissions []ToolPermissionEntry `json:"permissions"`
}

type StrategyCount struct {
	Strategy string `json:"strategy"`
	Count    int    `json:"count"`
}

type StructuralSeparationConfig struct {
	Enabled                  bool           `json:"enabled"`
	TemplateFormat           TemplateFormat `json:"templateFormat"`
	SystemSection            string         `json:"systemSection"`
	UserSection              string         `json:"userSection"`
	RetrievedSection         string         `json:"retrievedSection"`
	ForbidInstructionsInData bool           `json:"forbidInstructionsInData"`
	QuoteUserContent         bool           `json:"quoteUserContent"`
	MarkRetrievedAsUntrusted bool           `json:"markRetrievedAsUntrusted"`
}

type StructuralSeparationInput struct {
	Enabled                  *bool           `json:"enabled,omitempty"`
	TemplateFormat           *TemplateFormat `json:"templateFormat,omitempty"`
	SystemSection            *string         `json:"systemSection,omitempty"`
	UserSection              *string         `json:"userSection,omitempty"`
	RetrievedSection         *string         `json:"retrievedSection,omitempty"`
	ForbidInstructionsInData *bool           `json:"forbidInstructionsInData,omitempty"`
	QuoteUserContent         *bool           `json:"quoteUserContent,omitempty"`
	MarkRetrievedAsUntrusted *bool           `json:"markRetrievedAsUntrusted,omitempty"`
}

type Subscription struct {
}

type SystemPromptProtectionConfig struct {
	Enabled                  bool   `json:"enabled"`
	DetectExtractionAttempts bool   `json:"detectExtractionAttempts"`
	AddAntiExtractionSuffix  bool   `json:"addAntiExtractionSuffix"`
	AntiExtractionSuffix     string `json:"antiExtractionSuffix"`
	CanaryEnabled            bool   `json:"canaryEnabled"`
	CanaryToken              string `json:"canaryToken"`
	CanaryAlertOnLeak        bool   `json:"canaryAlertOnLeak"`
	CanaryWebhook            string `json:"canaryWebhook"`
}

type SystemPromptProtectionInput struct {
	Enabled                  *bool   `json:"enabled,omitempty"`
	DetectExtractionAttempts *bool   `json:"detectExtractionAttempts,omitempty"`
	AddAntiExtractionSuffix  *bool   `json:"addAntiExtractionSuffix,omitempty"`
	AntiExtractionSuffix     *string `json:"antiExtractionSuffix,omitempty"`
	CanaryEnabled            *bool   `json:"canaryEnabled,omitempty"`
	CanaryToken              *string `json:"canaryToken,omitempty"`
	CanaryAlertOnLeak        *bool   `json:"canaryAlertOnLeak,omitempty"`
	CanaryWebhook            *string `json:"canaryWebhook,omitempty"`
}

type TaskModelMapping struct {
	TaskType string   `json:"taskType"`
	Models   []string `json:"models"`
}

type TaskModelMappingInput struct {
	TaskType string   `json:"taskType"`
	Models   []string `json:"models"`
}

type Tenant struct {
	ID                 string          `json:"id"`
	Name               string          `json:"name"`
	Slug               string          `json:"slug"`
	Email              string          `json:"email"`
	Status             TenantStatus    `json:"status"`
	Tier               TenantTier      `json:"tier"`
	Settings           *TenantSettings `json:"settings,omitempty"`
	Quotas             *TenantQuotas   `json:"quotas,omitempty"`
	PlanLimits         *PlanLimits     `json:"planLimits"`
	PlanLimitsOverride *PlanLimits     `json:"planLimitsOverride,omitempty"`
	CreatedAt          time.Time       `json:"createdAt"`
	UpdatedAt          time.Time       `json:"updatedAt"`
}

type TenantQuotas struct {
	MaxRequestsPerMinute int     `json:"maxRequestsPerMinute"`
	MaxRequestsPerDay    int     `json:"maxRequestsPerDay"`
	MaxTokensPerDay      int     `json:"maxTokensPerDay"`
	MaxCostPerMonthUsd   float64 `json:"maxCostPerMonthUSD"`
}

type TenantSettings struct {
	DefaultModel          *string `json:"defaultModel,omitempty"`
	MaxConcurrentRequests *int    `json:"maxConcurrentRequests,omitempty"`
	WebhookURL            *string `json:"webhookUrl,omitempty"`
}

type TenantStats struct {
	TotalRequests int     `json:"totalRequests"`
	TotalTokens   int     `json:"totalTokens"`
	TotalCostUsd  float64 `json:"totalCostUSD"`
	ActiveAPIKeys int     `json:"activeApiKeys"`
	ActiveUsers   int     `json:"activeUsers"`
}

type TokenMetrics struct {
	TotalInput    int                   `json:"totalInput"`
	TotalOutput   int                   `json:"totalOutput"`
	TotalThinking int                   `json:"totalThinking"`
	TotalCost     float64               `json:"totalCost"`
	ByModel       []ModelTokenBreakdown `json:"byModel"`
}

type ToolCallBreakdown struct {
	ToolName     string `json:"toolName"`
	SuccessCount int    `json:"successCount"`
	FailureCount int    `json:"failureCount"`
	TotalCount   int    `json:"totalCount"`
}

type ToolCallMetrics struct {
	TotalCalls   int                 `json:"totalCalls"`
	SuccessCount int                 `json:"successCount"`
	FailureCount int                 `json:"failureCount"`
	SuccessRate  float64             `json:"successRate"`
	ByTool       []ToolCallBreakdown `json:"byTool"`
}

type ToolConfig struct {
	ToolName           string   `json:"toolName"`
	Enabled            bool     `json:"enabled"`
	AllowedParameters  []string `json:"allowedParameters"`
	BlockedParameters  []string `json:"blockedParameters"`
	MaxCallsPerRequest int      `json:"maxCallsPerRequest"`
	RequireApproval    bool     `json:"requireApproval"`
}

type ToolConfigInput struct {
	ToolName           string   `json:"toolName"`
	Enabled            *bool    `json:"enabled,omitempty"`
	AllowedParameters  []string `json:"allowedParameters,omitempty"`
	BlockedParameters  []string `json:"blockedParameters,omitempty"`
	MaxCallsPerRequest *int     `json:"maxCallsPerRequest,omitempty"`
	RequireApproval    *bool    `json:"requireApproval,omitempty"`
}

type ToolExecutionLog struct {
	ID          string    `json:"id"`
	ToolID      string    `json:"toolId"`
	ToolName    string    `json:"toolName"`
	RoleID      string    `json:"roleId"`
	APIKeyID    *string   `json:"apiKeyId,omitempty"`
	RequestID   *string   `json:"requestId,omitempty"`
	Status      string    `json:"status"`
	BlockReason *string   `json:"blockReason,omitempty"`
	ExecutedAt  time.Time `json:"executedAt"`
	Model       *string   `json:"model,omitempty"`
}

type ToolExecutionLogConnection struct {
	Items      []ToolExecutionLog `json:"items"`
	TotalCount int                `json:"totalCount"`
	HasMore    bool               `json:"hasMore"`
}

type ToolExecutionLogFilter struct {
	ToolID    *string    `json:"toolId,omitempty"`
	RoleID    *string    `json:"roleId,omitempty"`
	Status    *string    `json:"status,omitempty"`
	StartDate *time.Time `json:"startDate,omitempty"`
	EndDate   *time.Time `json:"endDate,omitempty"`
}

type ToolPermissionEntry struct {
	ToolID string               `json:"toolId"`
	Status ToolPermissionStatus `json:"status"`
	Reason *string              `json:"reason,omitempty"`
}

type ToolPolicies struct {
	AllowToolCalling       bool         `json:"allowToolCalling"`
	AllowedTools           []string     `json:"allowedTools"`
	BlockedTools           []string     `json:"blockedTools"`
	ToolConfigs            []ToolConfig `json:"toolConfigs"`
	MaxToolCallsPerRequest int          `json:"maxToolCallsPerRequest"`
	RequireToolApproval    bool         `json:"requireToolApproval"`
}

type ToolPoliciesInput struct {
	AllowToolCalling       *bool             `json:"allowToolCalling,omitempty"`
	AllowedTools           []string          `json:"allowedTools,omitempty"`
	BlockedTools           []string          `json:"blockedTools,omitempty"`
	ToolConfigs            []ToolConfigInput `json:"toolConfigs,omitempty"`
	MaxToolCallsPerRequest *int              `json:"maxToolCallsPerRequest,omitempty"`
	RequireToolApproval    *bool             `json:"requireToolApproval,omitempty"`
}

type ToolRolePermission struct {
	ID             string               `json:"id"`
	Tool           *DiscoveredTool      `json:"tool"`
	Role           *Role                `json:"role"`
	Status         ToolPermissionStatus `json:"status"`
	DecidedBy      *string              `json:"decidedBy,omitempty"`
	DecidedByEmail *string              `json:"decidedByEmail,omitempty"`
	DecidedAt      *time.Time           `json:"decidedAt,omitempty"`
	DecisionReason *string              `json:"decisionReason,omitempty"`
	CreatedAt      time.Time            `json:"createdAt"`
	UpdatedAt      time.Time            `json:"updatedAt"`
}

type ToolSearchInput struct {
	Query         string          `json:"query"`
	RoleID        *string         `json:"roleId,omitempty"`
	Strategy      *SearchStrategy `json:"strategy,omitempty"`
	ServerIds     []string        `json:"serverIds,omitempty"`
	Categories    []string        `json:"categories,omitempty"`
	MaxResults    *int            `json:"maxResults,omitempty"`
	MinScore      *float64        `json:"minScore,omitempty"`
	IncludeSchema *bool           `json:"includeSchema,omitempty"`
}

type ToolSearchResponse struct {
	Tools          []ToolSearchResult `json:"tools"`
	Query          string             `json:"query"`
	TotalAvailable int                `json:"totalAvailable"`
	TotalAllowed   int                `json:"totalAllowed"`
}

type ToolSearchResult struct {
	Tool         *MCPTool `json:"tool"`
	ServerID     string   `json:"serverId"`
	ServerName   string   `json:"serverName"`
	Score        float64  `json:"score"`
	MatchReason  *string  `json:"matchReason,omitempty"`
	DeferLoading bool     `json:"deferLoading"`
	ToolRef      string   `json:"toolRef"`
}

type ToolWithPermission struct {
	Tool           *DiscoveredTool      `json:"tool"`
	Status         ToolPermissionStatus `json:"status"`
	DecidedBy      *string              `json:"decidedBy,omitempty"`
	DecidedByEmail *string              `json:"decidedByEmail,omitempty"`
	DecidedAt      *time.Time           `json:"decidedAt,omitempty"`
	DecisionReason *string              `json:"decisionReason,omitempty"`
}

type UpdateAPIKeyInput struct {
	Name    *string `json:"name,omitempty"`
	RoleID  *string `json:"roleId,omitempty"`
	GroupID *string `json:"groupId,omitempty"`
}

type UpdateBudgetAlertInput struct {
	Name      *string  `json:"name,omitempty"`
	Threshold *float64 `json:"threshold,omitempty"`
	Enabled   *bool    `json:"enabled,omitempty"`
}

type UpdateGroupInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	RoleIds     []string `json:"roleIds,omitempty"`
}

type UpdateMCPServerInput struct {
	Name                *string             `json:"name,omitempty"`
	Description         *string             `json:"description,omitempty"`
	Endpoint            *string             `json:"endpoint,omitempty"`
	AuthType            *MCPAuthType        `json:"authType,omitempty"`
	AuthConfig          *MCPAuthConfigInput `json:"authConfig,omitempty"`
	Tags                []string            `json:"tags,omitempty"`
	AutoSync            *bool               `json:"autoSync,omitempty"`
	SyncIntervalMinutes *int                `json:"syncIntervalMinutes,omitempty"`
}

type UpdateProviderAPIKeyInput struct {
	ID              string  `json:"id"`
	Name            *string `json:"name,omitempty"`
	Priority        *int    `json:"priority,omitempty"`
	Enabled         *bool   `json:"enabled,omitempty"`
	APIKey          *string `json:"apiKey,omitempty"`
	AccessKeyID     *string `json:"accessKeyId,omitempty"`
	SecretAccessKey *string `json:"secretAccessKey,omitempty"`
}

type UpdateProviderInput struct {
	Provider           Provider                 `json:"provider"`
	Enabled            bool                     `json:"enabled"`
	APIKey             *string                  `json:"apiKey,omitempty"`
	BaseURL            *string                  `json:"baseUrl,omitempty"`
	Region             *string                  `json:"region,omitempty"`
	RegionPrefix       *string                  `json:"regionPrefix,omitempty"`
	AccessKeyID        *string                  `json:"accessKeyId,omitempty"`
	SecretAccessKey    *string                  `json:"secretAccessKey,omitempty"`
	ResourceName       *string                  `json:"resourceName,omitempty"`
	APIVersion         *string                  `json:"apiVersion,omitempty"`
	ModelsURL          *string                  `json:"modelsUrl,omitempty"`
	ConnectionSettings *ConnectionSettingsInput `json:"connectionSettings,omitempty"`
}

type UpdateRoleInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	IsDefault   *bool   `json:"isDefault,omitempty"`
}

type UpdateTenantInput struct {
	Name               *string          `json:"name,omitempty"`
	Email              *string          `json:"email,omitempty"`
	Status             *TenantStatus    `json:"status,omitempty"`
	Tier               *TenantTier      `json:"tier,omitempty"`
	PlanLimitsOverride *PlanLimitsInput `json:"planLimitsOverride,omitempty"`
}

type User struct {
	ID             string     `json:"id"`
	Email          string     `json:"email"`
	Name           string     `json:"name"`
	Role           string     `json:"role"`
	Status         string     `json:"status"`
	CreatedAt      time.Time  `json:"createdAt"`
	CreatedBy      *string    `json:"createdBy,omitempty"`
	CreatedByEmail *string    `json:"createdByEmail,omitempty"`
	LastLoginAt    *time.Time `json:"lastLoginAt,omitempty"`
}

type WeightedRoutingConfig struct {
	Weights []ProviderWeight `json:"weights"`
}

type WeightedRoutingConfigInput struct {
	Weights []ProviderWeightInput `json:"weights,omitempty"`
}

type AlertPeriod string

const (
	AlertPeriodDaily   AlertPeriod = "DAILY"
	AlertPeriodWeekly  AlertPeriod = "WEEKLY"
	AlertPeriodMonthly AlertPeriod = "MONTHLY"
)

var AllAlertPeriod = []AlertPeriod{
	AlertPeriodDaily,
	AlertPeriodWeekly,
	AlertPeriodMonthly,
}

func (e AlertPeriod) IsValid() bool {
	switch e {
	case AlertPeriodDaily, AlertPeriodWeekly, AlertPeriodMonthly:
		return true
	}
	return false
}

func (e AlertPeriod) String() string {
	return string(e)
}

func (e *AlertPeriod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertPeriod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertPeriod", str)
	}
	return nil
}

func (e AlertPeriod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertPeriod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertPeriod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AlertType string

const (
	AlertTypeCost     AlertType = "COST"
	AlertTypeTokens   AlertType = "TOKENS"
	AlertTypeRequests AlertType = "REQUESTS"
)

var AllAlertType = []AlertType{
	AlertTypeCost,
	AlertTypeTokens,
	AlertTypeRequests,
}

func (e AlertType) IsValid() bool {
	switch e {
	case AlertTypeCost, AlertTypeTokens, AlertTypeRequests:
		return true
	}
	return false
}

func (e AlertType) String() string {
	return string(e)
}

func (e *AlertType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertType", str)
	}
	return nil
}

func (e AlertType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AuditAction string

const (
	AuditActionCreate AuditAction = "CREATE"
	AuditActionUpdate AuditAction = "UPDATE"
	AuditActionDelete AuditAction = "DELETE"
	AuditActionRevoke AuditAction = "REVOKE"
	AuditActionLogin  AuditAction = "LOGIN"
	AuditActionLogout AuditAction = "LOGOUT"
)

var AllAuditAction = []AuditAction{
	AuditActionCreate,
	AuditActionUpdate,
	AuditActionDelete,
	AuditActionRevoke,
	AuditActionLogin,
	AuditActionLogout,
}

func (e AuditAction) IsValid() bool {
	switch e {
	case AuditActionCreate, AuditActionUpdate, AuditActionDelete, AuditActionRevoke, AuditActionLogin, AuditActionLogout:
		return true
	}
	return false
}

func (e AuditAction) String() string {
	return string(e)
}

func (e *AuditAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuditAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuditAction", str)
	}
	return nil
}

func (e AuditAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuditAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuditAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AuditResourceType string

const (
	AuditResourceTypeRole     AuditResourceType = "ROLE"
	AuditResourceTypePolicy   AuditResourceType = "POLICY"
	AuditResourceTypeGroup    AuditResourceType = "GROUP"
	AuditResourceTypeAPIKey   AuditResourceType = "API_KEY"
	AuditResourceTypeUser     AuditResourceType = "USER"
	AuditResourceTypeProvider AuditResourceType = "PROVIDER"
	AuditResourceTypeTenant   AuditResourceType = "TENANT"
	AuditResourceTypeSession  AuditResourceType = "SESSION"
)

var AllAuditResourceType = []AuditResourceType{
	AuditResourceTypeRole,
	AuditResourceTypePolicy,
	AuditResourceTypeGroup,
	AuditResourceTypeAPIKey,
	AuditResourceTypeUser,
	AuditResourceTypeProvider,
	AuditResourceTypeTenant,
	AuditResourceTypeSession,
}

func (e AuditResourceType) IsValid() bool {
	switch e {
	case AuditResourceTypeRole, AuditResourceTypePolicy, AuditResourceTypeGroup, AuditResourceTypeAPIKey, AuditResourceTypeUser, AuditResourceTypeProvider, AuditResourceTypeTenant, AuditResourceTypeSession:
		return true
	}
	return false
}

func (e AuditResourceType) String() string {
	return string(e)
}

func (e *AuditResourceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuditResourceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuditResourceType", str)
	}
	return nil
}

func (e AuditResourceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuditResourceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuditResourceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BudgetExceededAction string

const (
	BudgetExceededActionBlock    BudgetExceededAction = "BLOCK"
	BudgetExceededActionWarn     BudgetExceededAction = "WARN"
	BudgetExceededActionThrottle BudgetExceededAction = "THROTTLE"
)

var AllBudgetExceededAction = []BudgetExceededAction{
	BudgetExceededActionBlock,
	BudgetExceededActionWarn,
	BudgetExceededActionThrottle,
}

func (e BudgetExceededAction) IsValid() bool {
	switch e {
	case BudgetExceededActionBlock, BudgetExceededActionWarn, BudgetExceededActionThrottle:
		return true
	}
	return false
}

func (e BudgetExceededAction) String() string {
	return string(e)
}

func (e *BudgetExceededAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BudgetExceededAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BudgetExceededAction", str)
	}
	return nil
}

func (e BudgetExceededAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BudgetExceededAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BudgetExceededAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DetectionAction string

const (
	DetectionActionBlock      DetectionAction = "BLOCK"
	DetectionActionWarn       DetectionAction = "WARN"
	DetectionActionLog        DetectionAction = "LOG"
	DetectionActionQuarantine DetectionAction = "QUARANTINE"
	DetectionActionTransform  DetectionAction = "TRANSFORM"
)

var AllDetectionAction = []DetectionAction{
	DetectionActionBlock,
	DetectionActionWarn,
	DetectionActionLog,
	DetectionActionQuarantine,
	DetectionActionTransform,
}

func (e DetectionAction) IsValid() bool {
	switch e {
	case DetectionActionBlock, DetectionActionWarn, DetectionActionLog, DetectionActionQuarantine, DetectionActionTransform:
		return true
	}
	return false
}

func (e DetectionAction) String() string {
	return string(e)
}

func (e *DetectionAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DetectionAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DetectionAction", str)
	}
	return nil
}

func (e DetectionAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DetectionAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DetectionAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DetectionMethod string

const (
	DetectionMethodRules  DetectionMethod = "RULES"
	DetectionMethodMl     DetectionMethod = "ML"
	DetectionMethodHybrid DetectionMethod = "HYBRID"
)

var AllDetectionMethod = []DetectionMethod{
	DetectionMethodRules,
	DetectionMethodMl,
	DetectionMethodHybrid,
}

func (e DetectionMethod) IsValid() bool {
	switch e {
	case DetectionMethodRules, DetectionMethodMl, DetectionMethodHybrid:
		return true
	}
	return false
}

func (e DetectionMethod) String() string {
	return string(e)
}

func (e *DetectionMethod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DetectionMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DetectionMethod", str)
	}
	return nil
}

func (e DetectionMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DetectionMethod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DetectionMethod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DetectionSensitivity string

const (
	DetectionSensitivityLow      DetectionSensitivity = "LOW"
	DetectionSensitivityMedium   DetectionSensitivity = "MEDIUM"
	DetectionSensitivityHigh     DetectionSensitivity = "HIGH"
	DetectionSensitivityParanoid DetectionSensitivity = "PARANOID"
)

var AllDetectionSensitivity = []DetectionSensitivity{
	DetectionSensitivityLow,
	DetectionSensitivityMedium,
	DetectionSensitivityHigh,
	DetectionSensitivityParanoid,
}

func (e DetectionSensitivity) IsValid() bool {
	switch e {
	case DetectionSensitivityLow, DetectionSensitivityMedium, DetectionSensitivityHigh, DetectionSensitivityParanoid:
		return true
	}
	return false
}

func (e DetectionSensitivity) String() string {
	return string(e)
}

func (e *DetectionSensitivity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DetectionSensitivity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DetectionSensitivity", str)
	}
	return nil
}

func (e DetectionSensitivity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DetectionSensitivity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DetectionSensitivity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MCPAuthType string

const (
	MCPAuthTypeNone   MCPAuthType = "NONE"
	MCPAuthTypeAPIKey MCPAuthType = "API_KEY"
	MCPAuthTypeBearer MCPAuthType = "BEARER"
	MCPAuthTypeOauth2 MCPAuthType = "OAUTH2"
	MCPAuthTypeBasic  MCPAuthType = "BASIC"
	MCPAuthTypeMtls   MCPAuthType = "MTLS"
	MCPAuthTypeAWSIam MCPAuthType = "AWS_IAM"
)

var AllMCPAuthType = []MCPAuthType{
	MCPAuthTypeNone,
	MCPAuthTypeAPIKey,
	MCPAuthTypeBearer,
	MCPAuthTypeOauth2,
	MCPAuthTypeBasic,
	MCPAuthTypeMtls,
	MCPAuthTypeAWSIam,
}

func (e MCPAuthType) IsValid() bool {
	switch e {
	case MCPAuthTypeNone, MCPAuthTypeAPIKey, MCPAuthTypeBearer, MCPAuthTypeOauth2, MCPAuthTypeBasic, MCPAuthTypeMtls, MCPAuthTypeAWSIam:
		return true
	}
	return false
}

func (e MCPAuthType) String() string {
	return string(e)
}

func (e *MCPAuthType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MCPAuthType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MCPAuthType", str)
	}
	return nil
}

func (e MCPAuthType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MCPAuthType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MCPAuthType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MCPChangeType string

const (
	MCPChangeTypeAdded    MCPChangeType = "ADDED"
	MCPChangeTypeRemoved  MCPChangeType = "REMOVED"
	MCPChangeTypeModified MCPChangeType = "MODIFIED"
)

var AllMCPChangeType = []MCPChangeType{
	MCPChangeTypeAdded,
	MCPChangeTypeRemoved,
	MCPChangeTypeModified,
}

func (e MCPChangeType) IsValid() bool {
	switch e {
	case MCPChangeTypeAdded, MCPChangeTypeRemoved, MCPChangeTypeModified:
		return true
	}
	return false
}

func (e MCPChangeType) String() string {
	return string(e)
}

func (e *MCPChangeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MCPChangeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MCPChangeType", str)
	}
	return nil
}

func (e MCPChangeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MCPChangeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MCPChangeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MCPServerStatus string

const (
	MCPServerStatusPending      MCPServerStatus = "PENDING"
	MCPServerStatusConnected    MCPServerStatus = "CONNECTED"
	MCPServerStatusDisconnected MCPServerStatus = "DISCONNECTED"
	MCPServerStatusError        MCPServerStatus = "ERROR"
	MCPServerStatusDisabled     MCPServerStatus = "DISABLED"
)

var AllMCPServerStatus = []MCPServerStatus{
	MCPServerStatusPending,
	MCPServerStatusConnected,
	MCPServerStatusDisconnected,
	MCPServerStatusError,
	MCPServerStatusDisabled,
}

func (e MCPServerStatus) IsValid() bool {
	switch e {
	case MCPServerStatusPending, MCPServerStatusConnected, MCPServerStatusDisconnected, MCPServerStatusError, MCPServerStatusDisabled:
		return true
	}
	return false
}

func (e MCPServerStatus) String() string {
	return string(e)
}

func (e *MCPServerStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MCPServerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MCPServerStatus", str)
	}
	return nil
}

func (e MCPServerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MCPServerStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MCPServerStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MCPServerType string

const (
	MCPServerTypeStdio     MCPServerType = "STDIO"
	MCPServerTypeSse       MCPServerType = "SSE"
	MCPServerTypeWebsocket MCPServerType = "WEBSOCKET"
)

var AllMCPServerType = []MCPServerType{
	MCPServerTypeStdio,
	MCPServerTypeSse,
	MCPServerTypeWebsocket,
}

func (e MCPServerType) IsValid() bool {
	switch e {
	case MCPServerTypeStdio, MCPServerTypeSse, MCPServerTypeWebsocket:
		return true
	}
	return false
}

func (e MCPServerType) String() string {
	return string(e)
}

func (e *MCPServerType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MCPServerType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MCPServerType", str)
	}
	return nil
}

func (e MCPServerType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MCPServerType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MCPServerType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MCPToolVisibility string

const (
	MCPToolVisibilityDeny   MCPToolVisibility = "DENY"
	MCPToolVisibilitySearch MCPToolVisibility = "SEARCH"
	MCPToolVisibilityAllow  MCPToolVisibility = "ALLOW"
)

var AllMCPToolVisibility = []MCPToolVisibility{
	MCPToolVisibilityDeny,
	MCPToolVisibilitySearch,
	MCPToolVisibilityAllow,
}

func (e MCPToolVisibility) IsValid() bool {
	switch e {
	case MCPToolVisibilityDeny, MCPToolVisibilitySearch, MCPToolVisibilityAllow:
		return true
	}
	return false
}

func (e MCPToolVisibility) String() string {
	return string(e)
}

func (e *MCPToolVisibility) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MCPToolVisibility(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MCPToolVisibility", str)
	}
	return nil
}

func (e MCPToolVisibility) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MCPToolVisibility) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MCPToolVisibility) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OutputViolationAction string

const (
	OutputViolationActionBlock      OutputViolationAction = "BLOCK"
	OutputViolationActionRedact     OutputViolationAction = "REDACT"
	OutputViolationActionWarn       OutputViolationAction = "WARN"
	OutputViolationActionLog        OutputViolationAction = "LOG"
	OutputViolationActionRegenerate OutputViolationAction = "REGENERATE"
)

var AllOutputViolationAction = []OutputViolationAction{
	OutputViolationActionBlock,
	OutputViolationActionRedact,
	OutputViolationActionWarn,
	OutputViolationActionLog,
	OutputViolationActionRegenerate,
}

func (e OutputViolationAction) IsValid() bool {
	switch e {
	case OutputViolationActionBlock, OutputViolationActionRedact, OutputViolationActionWarn, OutputViolationActionLog, OutputViolationActionRegenerate:
		return true
	}
	return false
}

func (e OutputViolationAction) String() string {
	return string(e)
}

func (e *OutputViolationAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OutputViolationAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OutputViolationAction", str)
	}
	return nil
}

func (e OutputViolationAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OutputViolationAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OutputViolationAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PIIAction string

const (
	PIIActionBlock   PIIAction = "BLOCK"
	PIIActionRedact  PIIAction = "REDACT"
	PIIActionRewrite PIIAction = "REWRITE"
	PIIActionWarn    PIIAction = "WARN"
	PIIActionLog     PIIAction = "LOG"
)

var AllPIIAction = []PIIAction{
	PIIActionBlock,
	PIIActionRedact,
	PIIActionRewrite,
	PIIActionWarn,
	PIIActionLog,
}

func (e PIIAction) IsValid() bool {
	switch e {
	case PIIActionBlock, PIIActionRedact, PIIActionRewrite, PIIActionWarn, PIIActionLog:
		return true
	}
	return false
}

func (e PIIAction) String() string {
	return string(e)
}

func (e *PIIAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PIIAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PIIAction", str)
	}
	return nil
}

func (e PIIAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PIIAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PIIAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Provider string

const (
	ProviderOpenai      Provider = "OPENAI"
	ProviderAnthropic   Provider = "ANTHROPIC"
	ProviderGemini      Provider = "GEMINI"
	ProviderBedrock     Provider = "BEDROCK"
	ProviderAzureOpenai Provider = "AZURE_OPENAI"
	ProviderOllama      Provider = "OLLAMA"
	ProviderGroq        Provider = "GROQ"
	ProviderMistral     Provider = "MISTRAL"
	ProviderTogether    Provider = "TOGETHER"
	ProviderCohere      Provider = "COHERE"
)

var AllProvider = []Provider{
	ProviderOpenai,
	ProviderAnthropic,
	ProviderGemini,
	ProviderBedrock,
	ProviderAzureOpenai,
	ProviderOllama,
	ProviderGroq,
	ProviderMistral,
	ProviderTogether,
	ProviderCohere,
}

func (e Provider) IsValid() bool {
	switch e {
	case ProviderOpenai, ProviderAnthropic, ProviderGemini, ProviderBedrock, ProviderAzureOpenai, ProviderOllama, ProviderGroq, ProviderMistral, ProviderTogether, ProviderCohere:
		return true
	}
	return false
}

func (e Provider) String() string {
	return string(e)
}

func (e *Provider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Provider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Provider", str)
	}
	return nil
}

func (e Provider) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Provider) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Provider) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RoutingStrategy string

const (
	RoutingStrategyCost       RoutingStrategy = "COST"
	RoutingStrategyLatency    RoutingStrategy = "LATENCY"
	RoutingStrategyWeighted   RoutingStrategy = "WEIGHTED"
	RoutingStrategyRoundRobin RoutingStrategy = "ROUND_ROBIN"
	RoutingStrategyCapability RoutingStrategy = "CAPABILITY"
)

var AllRoutingStrategy = []RoutingStrategy{
	RoutingStrategyCost,
	RoutingStrategyLatency,
	RoutingStrategyWeighted,
	RoutingStrategyRoundRobin,
	RoutingStrategyCapability,
}

func (e RoutingStrategy) IsValid() bool {
	switch e {
	case RoutingStrategyCost, RoutingStrategyLatency, RoutingStrategyWeighted, RoutingStrategyRoundRobin, RoutingStrategyCapability:
		return true
	}
	return false
}

func (e RoutingStrategy) String() string {
	return string(e)
}

func (e *RoutingStrategy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoutingStrategy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoutingStrategy", str)
	}
	return nil
}

func (e RoutingStrategy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RoutingStrategy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RoutingStrategy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchStrategy string

const (
	SearchStrategyRegex    SearchStrategy = "REGEX"
	SearchStrategyBm25     SearchStrategy = "BM25"
	SearchStrategySemantic SearchStrategy = "SEMANTIC"
	SearchStrategyHybrid   SearchStrategy = "HYBRID"
)

var AllSearchStrategy = []SearchStrategy{
	SearchStrategyRegex,
	SearchStrategyBm25,
	SearchStrategySemantic,
	SearchStrategyHybrid,
}

func (e SearchStrategy) IsValid() bool {
	switch e {
	case SearchStrategyRegex, SearchStrategyBm25, SearchStrategySemantic, SearchStrategyHybrid:
		return true
	}
	return false
}

func (e SearchStrategy) String() string {
	return string(e)
}

func (e *SearchStrategy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchStrategy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchStrategy", str)
	}
	return nil
}

func (e SearchStrategy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchStrategy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchStrategy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TemplateFormat string

const (
	TemplateFormatXML      TemplateFormat = "XML"
	TemplateFormatJSON     TemplateFormat = "JSON"
	TemplateFormatMarkdown TemplateFormat = "MARKDOWN"
)

var AllTemplateFormat = []TemplateFormat{
	TemplateFormatXML,
	TemplateFormatJSON,
	TemplateFormatMarkdown,
}

func (e TemplateFormat) IsValid() bool {
	switch e {
	case TemplateFormatXML, TemplateFormatJSON, TemplateFormatMarkdown:
		return true
	}
	return false
}

func (e TemplateFormat) String() string {
	return string(e)
}

func (e *TemplateFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TemplateFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TemplateFormat", str)
	}
	return nil
}

func (e TemplateFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TemplateFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TemplateFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TenantStatus string

const (
	TenantStatusActive    TenantStatus = "ACTIVE"
	TenantStatusSuspended TenantStatus = "SUSPENDED"
	TenantStatusPending   TenantStatus = "PENDING"
)

var AllTenantStatus = []TenantStatus{
	TenantStatusActive,
	TenantStatusSuspended,
	TenantStatusPending,
}

func (e TenantStatus) IsValid() bool {
	switch e {
	case TenantStatusActive, TenantStatusSuspended, TenantStatusPending:
		return true
	}
	return false
}

func (e TenantStatus) String() string {
	return string(e)
}

func (e *TenantStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TenantStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TenantStatus", str)
	}
	return nil
}

func (e TenantStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TenantStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TenantStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TenantTier string

const (
	TenantTierFree         TenantTier = "FREE"
	TenantTierStarter      TenantTier = "STARTER"
	TenantTierProfessional TenantTier = "PROFESSIONAL"
	TenantTierEnterprise   TenantTier = "ENTERPRISE"
)

var AllTenantTier = []TenantTier{
	TenantTierFree,
	TenantTierStarter,
	TenantTierProfessional,
	TenantTierEnterprise,
}

func (e TenantTier) IsValid() bool {
	switch e {
	case TenantTierFree, TenantTierStarter, TenantTierProfessional, TenantTierEnterprise:
		return true
	}
	return false
}

func (e TenantTier) String() string {
	return string(e)
}

func (e *TenantTier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TenantTier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TenantTier", str)
	}
	return nil
}

func (e TenantTier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TenantTier) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TenantTier) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ToolPermissionStatus string

const (
	ToolPermissionStatusPending ToolPermissionStatus = "PENDING"
	ToolPermissionStatusAllowed ToolPermissionStatus = "ALLOWED"
	ToolPermissionStatusDenied  ToolPermissionStatus = "DENIED"
	ToolPermissionStatusRemoved ToolPermissionStatus = "REMOVED"
)

var AllToolPermissionStatus = []ToolPermissionStatus{
	ToolPermissionStatusPending,
	ToolPermissionStatusAllowed,
	ToolPermissionStatusDenied,
	ToolPermissionStatusRemoved,
}

func (e ToolPermissionStatus) IsValid() bool {
	switch e {
	case ToolPermissionStatusPending, ToolPermissionStatusAllowed, ToolPermissionStatusDenied, ToolPermissionStatusRemoved:
		return true
	}
	return false
}

func (e ToolPermissionStatus) String() string {
	return string(e)
}

func (e *ToolPermissionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ToolPermissionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ToolPermissionStatus", str)
	}
	return nil
}

func (e ToolPermissionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ToolPermissionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ToolPermissionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UnicodeNormForm string

const (
	UnicodeNormFormNfc  UnicodeNormForm = "NFC"
	UnicodeNormFormNfkc UnicodeNormForm = "NFKC"
	UnicodeNormFormNfd  UnicodeNormForm = "NFD"
	UnicodeNormFormNfkd UnicodeNormForm = "NFKD"
)

var AllUnicodeNormForm = []UnicodeNormForm{
	UnicodeNormFormNfc,
	UnicodeNormFormNfkc,
	UnicodeNormFormNfd,
	UnicodeNormFormNfkd,
}

func (e UnicodeNormForm) IsValid() bool {
	switch e {
	case UnicodeNormFormNfc, UnicodeNormFormNfkc, UnicodeNormFormNfd, UnicodeNormFormNfkd:
		return true
	}
	return false
}

func (e UnicodeNormForm) String() string {
	return string(e)
}

func (e *UnicodeNormForm) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UnicodeNormForm(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UnicodeNormForm", str)
	}
	return nil
}

func (e UnicodeNormForm) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UnicodeNormForm) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UnicodeNormForm) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
